project: BeyondDetection
name: vega_train_timm
program: train_timm.py


command:
  - ${env}
  # - echo
  - srun
  - "--nodes=1"
  - "--cpus-per-task=12"
  - "--gpus=4"
  - "-p gpu"
  - "--ntasks-per-node=4"
  - "--exclusive"
  - python3
  - ${program}
  - ${args}
  - "--devices"
  - "0"
  - "1"
  - "2"
  - "3"



method: random
metric:
  goal: minimize
  name: val_loss

parameters:
  model_name:
    values:
      - swin_large_patch4_window12_384.ms_in22k_ft_in1k
    distribution: categorical
  batch_size:
    values:
      - 1
    distribution: categorical
    
    
  seq_len:
    values:
      - 8
      - 16
      - 32

    distribution: categorical

  accumulate_grad_batches:
    values:
      - 1
    distribution: categorical

  dropout:
    distribution: categorical
    values:
      - 0.0
      - 0.1

  max_epochs:
    values:
      - 16
      - 32
      - 48
      - 64
    distribution: categorical

  loss:
    values:
      - "rmse"
      - "mae"
    distribution: categorical

  augmentation:
    values:
      - False

    distribution: categorical

  augment_prob:
    values:
      - 0.0
    distribution: categorical

  drop_path_rate:
    values:
      - 0.0
      - 0.2
    distribution: categorical

  val_split:
    values:
      - 0.1
    distribution: categorical

  weight_decay:
    values:
      - 0.01
      - 0.1
      - 0.001
    distribution: categorical
  
  seed:
    values:
      - -1
      - 1126
    distribution: categorical

  pretrained_backbone:
    values:
      - "/ceph/hpc/data/st2207-pgp-users/models_luka/swin_large_patch4_window12_384.ms_in22k_ft_in1k/swin_large_patch4_window12_384.ms_in22k_ft_in1k-epoch=12-train_loss=0.03.ckpt"
      # - "./borut_models/convnext_xlarge_384_in22ft1k_30.pth"
    distribution: categorical


  
  



  # devices:
  #   value:
  #     - [0,1,2,3]
  #   distribution: constant

  # dataset_root:
  #   value:
  #     - "/ceph/hpc/data/st2207-pgp-users/ldragar/dataset/"
  #   distribution: constant
